### ISSUE TITLE
How to download and Get the complete dataset 

### ISSUE THREAD

**Issue by EngineerSE** [mohaddad/COVID-FAKES#3]
@mohaddad  
I have few questions regarding this dataset
1. In your paper, you discussed about the ground truth data set, how can I get that data set?
2. I am unable to download the csv files and also there are only Tweetids in those files, how can I download and get the entire dataset  of tweets?
3. Are the csv files you uploaded are labeled test dataset or the result of your model?

Kindly guide me.
Thanks.

**Comment by dannydarvish** [comment]
You must hydrate the tweets to get the Twitter JSON from Twitter. You can google how to do that.

**Comment by EngineerSE** [comment]
> You must hydrate the tweets to get the Twitter JSON from Twitter. You can google how to do that.

**Comment by EngineerSE** [comment]
> You must hydrate the tweets to get the Twitter JSON from Twitter. You can google how to do that.

@dannydarvish I hydrated tweets through Hydrator, but out of around 75000 tweets, I was only able to hydrate 30

**Comment by mohaddad** [comment]
The problem is with the technique that you are using in retrieving the data related to each Tweet Id. I recommend you to use Twitter official API (limitations of the Twitter API (3,200 tweets per query)) (http://docs.tweepy.org/en/latest/getting_started.html). you might not be able to download all the Tweets; as they might be no longer available/accessible, most likely because they had been deleted by either the user or Twitter.
